### ISSUE TITLE
Code Formatting: Add linter to auto-format; consider using clang-format tool for this purpose

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [AmboVent-1690-108/AmboVent#21]
Add linter to auto-format; consider using clang-format. I volunteer. I'll figure it out.

This is a sub-issue of #11. Don't close #11 until all sub-issues are solved.

**Comment by nimrod46** [comment]
Just make sure to leave some work to other contributors ;)

**Comment by ElectricRCAircraftGuy** [comment]
Work is basically complete on this one. Please see email I sent to @nimrod46 and @giorakor
